## -----------------------------------------------------------------
## BUILD NETWORKS FOR BASELINE AND EXTINCTION/CC SCENARIOS
## 10KM
## SUPPORTING SCRIPTS - For workflow demo
## 
## Ceres Aug 2024
## -----------------------------------------------------------------

## RUN SIMUALTIONS FOR EACH LINE OF PARAMETERS FILE ----
## use a for loop so that necessary objects are stored in .GlobalEnv
for (params in parameters) {
  ## convert to named character vector
  params <- strsplit(params, split = " ")[[1]]
  ## remove any empty entries (generated by character alignment in file)
  params <- params[nchar(params) > 0]
  names(params) <- c("CC", "LUC", "IUCN", "doCC", "doNOdisp", "doLUC", "doPA")    ## order of parameters
  
  ## SCENARIO SPECs - hereafter objects must be assigned to .Global using <-
  doIUCN <- isTRUE(params[["IUCN"]] != "noIUCN")
  doCC <- as.logical(params[["doCC"]])            ## simulate climate change?
  doNOdisp <- as.logical(params[["doNOdisp"]])       ## simulate climate change, but no dispersal? can only be TRUE, if doCC is TRUE
  doLUC <- as.logical(params[["doLUC"]])          ## simulate land-use changes?
  doPA <- as.logical(params[["doPA"]])           ## simulate PAs? (i.e. land-use is unchanged inside PAs) can only be TRUE, if doLUC is TRUE
  
  file.suff <- ifelse(opt, "opthab_tresh", "allhab_tresh0")
  
  if (doCC) {
    outputs.dir <- "NetworkSims/IUCN_CC_sims_GlobCover"
    
    ## define scenario name
    if (!doNOdisp) scen <- "CC_ExtTrsh"
    if (doNOdisp) scen <- "CC_noInvs_ExtTrsh"  
    if (doLUC & !doPA) scen <- paste0("LUC_", scen)
    if (doLUC & doPA) scen <- paste0("PAs_LUC_", scen)
    if (doIUCN) scen <- paste0("IUCN_", scen)
    
  } else {
    if (doLUC) {
      outputs.dir <- "NetworkSims/IUCN_CC_sims_GlobCover"
      scen <- "LUC_ExtTrsh"
    
      if (doPA) scen <- paste0("PAs_", scen) 
      if (doIUCN) scen <- paste0("IUCN_", scen)
    } else {
      if (doIUCN) {
        outputs.dir <- "NetworkSims/IUCN_CC_sims_GlobCover"
        scen <- "IUCN_ExtTrsh"
      } else {
        outputs.dir <- "NetworkSims/Baseline_SDMpres_GlobCover"
        scen <- NULL
      }
    }
  }
  
  ## suffix for outputs file
  outfile.suff <- paste(params[["CC"]], params[["LUC"]], params[["IUCN"]], file.suff, sep = "_")
  
  ## --------------------------------------------------
  ## LOADING DATA
  ## --------------------------------------------------
  
  ## need to source HABITATdata first, as it is needed by SPPdata
  source("Dataprep/HABITATdata.R", local = TRUE)
  source("Dataprep/SPPdata.R", local = TRUE)
  
  ## --------------------------------------------------
  ## CALCULATING NETWORKS
  ## --------------------------------------------------
  
  ## "realised" networks are built using diet categories;
  ## network properties are calculated ignoring diet categories (except for trophic level)
  
  ## source network calc function - depends on parameters
  source("Tools/network_calc_FUN.R")
  
  ## get diet categories
  dietcat <- head(colnames(BARMdiet.binary), 11)   ## for fundamental links table
  
  ## Parellelisation
  ## clean wd before computations and reset memory
  rm(spp_fewObs); for (i in 1:10) gc()
  
  if (!useBLextthresh) {
    scen <- if (is.null(scen)) "No_ext_thresh" else file.path(scen, "No_ext_thresh")
    temp.folder <- paste(params[1], params[2], "Temp", sep = "_")
    
    parallelize.networkCalc(outputs.dir = outputs.dir, scen = scen, temp.folder = temp.folder,
                            do.pix = do.pix, noCPUs = noCPUs, parallel = parallel)
  } else {
    quantsNum <- if (all(quants == "all")) {
      1:ncol(ext.thresh)
    } else {
      if (any(!quants %in% names(ext.thresh))) {
        stop("Can't find all 'quants' in 'ext.thresh' table")
      } else {
        which(names(ext.thresh) %in% quants)
      }
    }
    for (j in quantsNum) {
      thresh <- ext.thresh[, j, drop =FALSE]
      scen2 <- if (is.null(scen)) paste0("ExtTrsh_", colnames(thresh)) else file.path(scen, paste0("ExtTrsh_", colnames(thresh)))
      temp.folder <- paste(params[1], params[2], "Temp", sep = "_")
      
      parallelize.networkCalc(outputs.dir = outputs.dir, scen = scen2, temp.folder = temp.folder, 
                              do.pix = do.pix, noCPUs = noCPUs, parallel = parallel)
    }
  }
}

q("no")
